---
- name: Configurations virtual machine
  hosts: virtual_machine
  become: true
  gather_facts: no

  pre_tasks:
    - name: "[Ubuntu] Install Python"
      changed_when: false
      shell: "apt-get install -y python python3 && sudo update-alternatives --install /usr/local/bin/python python /usr/bin/python3 10"
      when: system.os_distribution == "Ubuntu"

    - name: "[Centos] Install Python"
      changed_when: false
      shell: "yum install -y python2 python36 && sudo alternatives --install /usr/local/bin/python python /usr/bin/python3 10"
      when: system.os_distribution == "CentOS" and system.os_version == "7"

  roles:
    - role: Ansible.Role.VM.ConfigurationSSH
      tags: [ssh]
      vars:
        os_distribution: "{{ system.os_distribution }}"