---
- name: Install packages
  hosts: virtual_machine
  become: true
  gather_facts: no
  
  roles:
    - role: Ansible.Role.VM.InstallPackages
      tags: [packages,pip,install]
      vars:
        os_distribution:        "{{ system.os_distribution }}"
        os_version:             "{{ system.os_version }}"
        repository_keys:        "{{ system.packages.repository_keys           | default('[]') }}"
        repositories:           "{{ system.packages.repositories              | default('[]') }}"
        packages_to_install:    "{{ system.packages.packages_to_install       | default('[]') }}"
        packages_to_remove:     "{{ system.packages.packages_to_remove        | default('[]') }}"
        pip_packages:           "{{ system.pip_packages                       | default('[]') }}"
        pip3_packages:          "{{ system.pip3_packages                      | default('[]') }}"